import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Script from "next/script";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import ReactQueryProviders from "./(hooks)/common/useReactQuery";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "YumYum",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    naver: any;
    Kakao: any; // 나중에 설명할 카카오 로그인을 위해 이 부분도 추가해주세요!
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Script
          src='https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.2.js'
          strategy='beforeInteractive'
        />
        <ReactQueryProviders>
          <Suspense>
            {children}
          </Suspense>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
