import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../../header";
import Script from "next/script";

export const metadata: Metadata = {
  title: "YumYum 맛집 상세 페이지",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div>
        {children}
      </div>
    </>
  );
}
